"""Added users discord id so username is irrelevent

Revision ID: 0c8ab4bfd0e7
Revises: e2a8dd59d296
Create Date: 2024-11-28 23:17:08.913187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8ab4bfd0e7'
down_revision: Union[str, None] = 'e2a8dd59d296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('discord_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'discord_id')
    # ### end Alembic commands ###
